### ISSUE TITLE
erpnext11 502 error

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-erpnext#14]
502 error, reset image and reinstall, also 502

RUNNING HANDLER [role_end : end_check_versions] ********************************
ok: [182.160.6.143] => {
    "end_check_versions.stdout_lines": [
        "Docker version 20.10.6, build 370c289",
        "Docker version 20.10.6, build 370c289",
        "phpmyadmin version: \"version\": \"5.1.0\",",
        "nginx version: nginx/1.20.0",
        "erpnext version:",
        "mariadb version:",
        "redis version: 6.2.3\",",
        "System version: CentOS 7.9",
        "Image name: ansible-erpnext"
    ]
}

**Comment by zengxc-1996** [comment]
tested: 
AWS linux2:
ok: [54.89.76.65] => {
    "end_check_versions.stdout_lines": [
        "Docker version 20.10.6, build 370c289",
        "Docker version 20.10.6, build 370c289",
        "phpmyadmin version: \"version\": \"5.1.0\",",
        "nginx version: nginx/1.20.0",
        "erpnext version: v11",
        "mariadb version: 10.3",
        "redis version: 6.2.3\",",
        "System version: Amazon 2",
        "Image name: erpnextzengxc-AmazonLinux2"

![image](https://user-images.githubusercontent.com/63622990/119448642-321be400-bd64-11eb-8985-dfd86a1de2c6.png)

**Comment by qiaofeng1227** [comment]
Done
