### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by hnczhjh** [Websoft9/ansible-erpnext#15]
## Language

- [x] Chinese
- [x] English

## Content error

Provide us with documentation errors, e.g spelling mistake, wrong screenshot, code syntax error.

* URL: https://support.websoft9.com/docs/erpnext/zh/admin-services.html
* Description: 
* Screenshot
![image](https://user-images.githubusercontent.com/86603933/126288892-ea03d27c-dae9-49af-b103-84dd3ba37e17.png)

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
Done
