### ISSUE TITLE
无法域名绑定，修改 Nginx虚拟机主机配置文件后重启还是无效。

### ISSUE THREAD

**Issue by huacong1** [Websoft9/ansible-erpnext#18]
修改 Nginx虚拟机主机配置文件后重启还是无效

**Comment by chendelin1982** [comment]
域名发给我，我这边访问试试

**Comment by huacong1** [comment]
ylzd.tk

**Comment by huacong1** [comment]
> 域名发给我，我这边访问试试
域名 ylzd.tk

提示
Not Found
ylzd.tk does not exist

**Comment by huacong1** [comment]
default.conf文件内容是这个
server {
    listen 80;
    server_name ylzd.tk;
    location / {
        proxy_pass  http://127.0.0.1:8000;
        proxy_redirect     off;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_max_temp_file_size 0;
        proxy_connect_timeout      90;
        proxy_send_timeout         90;
        proxy_read_timeout         90;
        proxy_buffer_size          4k;
        proxy_buffers              4 32k;
        proxy_busy_buffers_size    64k;
        proxy_temp_file_write_size 64k;

**Comment by chendelin1982** [comment]
绑定配置没有错。
查了下对应的域名，你是做了CDN，但域名没有真正解析到服务器上。
![image](https://user-images.githubusercontent.com/16741975/149602434-e4d62561-34a2-4170-b6d1-8ecf921b704f.png)

**Comment by huacong1** [comment]
我昨天重装了，下午再试试看

**Comment by huacong1** [comment]
现在是这个提示了
Not Found
ylzd.tk does not exist
我把CDN关了还是不行

**Comment by laozhou0731** [comment]
在 /data/wwwroot/erpnext 目录下，修改.env 环境变量  APP_SITE_URL 为域名信息，然后 docker-compose up -d 重启ERPNext
稍等片刻即可。

[文档参考](https://support.websoft9.com/docs/erpnext/zh/solution-more.html#%E5%9F%9F%E5%90%8D%E7%BB%91%E5%AE%9A)
